services:
  x_agent:
    image: sagarparker/twtagent_amd64:latest
    init: true
    restart: unless-stopped
    network_mode: host
    command: ["/opt/venv/bin/python", "/app/x_agent.py"]
    volumes:
      - /init-params/:/init-params/
      - shared_data:/app/shared_data
    env_file:
      - /init-params/xagent/.env
  verifier:
    image: sagarparker/twtagent_amd64:latest
    init: true
    restart: unless-stopped
    network_mode: host
    command: ["/opt/venv/bin/python", "/app/verifier.py"]
    volumes:
      - /init-params/:/init-params/
      - shared_data:/app/shared_data
    env_file:
      - /init-params/xagent/.env
  make_a_tweet:
    image: sagarparker/makeatweet:latest
    init: true
    restart: unless-stopped
    network_mode: host

volumes:
  shared_data: