services:
  x_agent:
    image: sagarparker/twtagenttest:latest
    init: true
    restart: unless-stopped
    network_mode: host
    command: ["/opt/venv/bin/python", "/app/x_agent.py"]
    volumes:
      - /init-params/:/init-params/
    env_file:
      - /init-params/xagent/.env
  verifier:
    image: sagarparker/twtagenttest:latest
    init: true
    restart: unless-stopped
    network_mode: host
    command: ["/opt/venv/bin/python", "/app/verifier.py"]
    ports:
      - "8888:8888"
    volumes:
      - /init-params/:/init-params/
    env_file:
      - /init-params/xagent/.env