services:
  x_agent:
    image: twtagent:latest
    init: true
    restart: unless-stopped
    command: ["/opt/venv/bin/python", "/app/x_agent.py"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - shared_data:/app/shared_data
  verifier:
    image: twtagent:latest
    init: true
    restart: unless-stopped
    command: ["/opt/venv/bin/python", "/app/verifier.py"]
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - shared_data:/app/shared_data
  kms_imitator:
    image: twtagent:latest
    init: true
    restart: unless-stopped
    command: ["/opt/venv/bin/python", "/app/kms_imitator.py"]
    ports:
      - "1100:1100"
volumes:
  shared_data: