services:
  x_agent:
    image: sagarparker/twtagent:latest
    init: true
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: ["/opt/venv/bin/python", "/app/x_agent.py"]
    env_file:
      - .env
  verifier:
    image: sagarparker/twtagent:latest
    init: true
    restart: unless-stopped
    ports:
      - "8888:8888"
    command: ["/opt/venv/bin/python", "/app/verifier.py"]
    env_file:
      - .env
