services:
  x_agent:
    image: sagarparker/twtagenttest:latest
    init: true
    restart: unless-stopped
    network_mode: host
    command: ["/opt/venv/bin/python", "/app/x_agent.py"]
  verifier:
    image: sagarparker/twtagenttest:latest
    init: true
    restart: unless-stopped
    network_mode: host
    command: ["/opt/venv/bin/python", "/app/verifier.py"]
